services:
  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: simple_bank
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d simple_bank"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DATA_SOURCE=postgres://root:password@postgres:5432/simple_bank?sslmode=disable
    depends_on:
      postgres:
        condition: service_healthy

