// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db_source

import (
	"database/sql"
)

type Account struct {
	ID        int64
	Owner     string
	Balance   int64
	Currency  string
	CreatedAt sql.NullTime
}

type Entry struct {
	ID        int64
	AccountID int64
	// Can be negative or positive
	Amount    int64
	CreatedAt sql.NullTime
}

type Transfer struct {
	ID            int64
	FromAccountID int64
	ToAccountID   int64
	// Can be only positive
	Amount    int64
	CreatedAt sql.NullTime
}
