// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: rpc_simple_bank.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_rpc_simple_bank_proto protoreflect.FileDescriptor

const file_rpc_simple_bank_proto_rawDesc = "" +
	"\n" +
	"\x15rpc_simple_bank.proto\x12\x02pb\x1a\n" +
	"user.proto2\xc8\x01\n" +
	"\n" +
	"SimpleBank\x12;\n" +
	"\n" +
	"CreateUser\x12\x15.pb.CreateUserRequest\x1a\x16.pb.CreateUserResponse\x124\n" +
	"\x05Login\x12\x14.pb.LoginUserRequest\x1a\x15.pb.LoginUserResponse\x12G\n" +
	"\x0eGetUserDetails\x12\x19.pb.GetUserDetailsRequest\x1a\x1a.pb.GetUserDetailsResponseB-Z+github.com/suhailmuhammed157/simple_bank/pbb\x06proto3"

var file_rpc_simple_bank_proto_goTypes = []any{
	(*CreateUserRequest)(nil),      // 0: pb.CreateUserRequest
	(*LoginUserRequest)(nil),       // 1: pb.LoginUserRequest
	(*GetUserDetailsRequest)(nil),  // 2: pb.GetUserDetailsRequest
	(*CreateUserResponse)(nil),     // 3: pb.CreateUserResponse
	(*LoginUserResponse)(nil),      // 4: pb.LoginUserResponse
	(*GetUserDetailsResponse)(nil), // 5: pb.GetUserDetailsResponse
}
var file_rpc_simple_bank_proto_depIdxs = []int32{
	0, // 0: pb.SimpleBank.CreateUser:input_type -> pb.CreateUserRequest
	1, // 1: pb.SimpleBank.Login:input_type -> pb.LoginUserRequest
	2, // 2: pb.SimpleBank.GetUserDetails:input_type -> pb.GetUserDetailsRequest
	3, // 3: pb.SimpleBank.CreateUser:output_type -> pb.CreateUserResponse
	4, // 4: pb.SimpleBank.Login:output_type -> pb.LoginUserResponse
	5, // 5: pb.SimpleBank.GetUserDetails:output_type -> pb.GetUserDetailsResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rpc_simple_bank_proto_init() }
func file_rpc_simple_bank_proto_init() {
	if File_rpc_simple_bank_proto != nil {
		return
	}
	file_user_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_simple_bank_proto_rawDesc), len(file_rpc_simple_bank_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_simple_bank_proto_goTypes,
		DependencyIndexes: file_rpc_simple_bank_proto_depIdxs,
	}.Build()
	File_rpc_simple_bank_proto = out.File
	file_rpc_simple_bank_proto_goTypes = nil
	file_rpc_simple_bank_proto_depIdxs = nil
}
