// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: rpc_simple_bank.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_rpc_simple_bank_proto protoreflect.FileDescriptor

const file_rpc_simple_bank_proto_rawDesc = "" +
	"\n" +
	"\x15rpc_simple_bank.proto\x12\x02pb\x1a\n" +
	"user.proto\x1a\raccount.proto\x1a\vtoken.proto2\xc4\x04\n" +
	"\n" +
	"SimpleBank\x12;\n" +
	"\n" +
	"CreateUser\x12\x15.pb.CreateUserRequest\x1a\x16.pb.CreateUserResponse\x124\n" +
	"\x05Login\x12\x14.pb.LoginUserRequest\x1a\x15.pb.LoginUserResponse\x12G\n" +
	"\x0eGetUserDetails\x12\x19.pb.GetUserDetailsRequest\x1a\x1a.pb.GetUserDetailsResponse\x12;\n" +
	"\n" +
	"UpdateUser\x12\x15.pb.UpdateUserRequest\x1a\x16.pb.UpdateUserResponse\x12;\n" +
	"\n" +
	"VerifyUser\x12\x15.pb.VerifyUserRequest\x1a\x16.pb.VerifyUserResponse\x12D\n" +
	"\rCreateAccount\x12\x18.pb.CreateAccountRequest\x1a\x19.pb.CreateAccountResponse\x12=\n" +
	"\x11GetAccountDetails\x12\t.pb.Empty\x1a\x1d.pb.GetAccountDetailsResponse\x12?\n" +
	"\fListAccounts\x12\x16.pb.ListAccountRequest\x1a\x17.pb.ListAccountResponse\x12:\n" +
	"\rIssueNewToken\x12\x13.pb.NewTokenRequest\x1a\x14.pb.NewTokenResponseB-Z+github.com/suhailmuhammed157/simple_bank/pbb\x06proto3"

var file_rpc_simple_bank_proto_goTypes = []any{
	(*CreateUserRequest)(nil),         // 0: pb.CreateUserRequest
	(*LoginUserRequest)(nil),          // 1: pb.LoginUserRequest
	(*GetUserDetailsRequest)(nil),     // 2: pb.GetUserDetailsRequest
	(*UpdateUserRequest)(nil),         // 3: pb.UpdateUserRequest
	(*VerifyUserRequest)(nil),         // 4: pb.VerifyUserRequest
	(*CreateAccountRequest)(nil),      // 5: pb.CreateAccountRequest
	(*Empty)(nil),                     // 6: pb.Empty
	(*ListAccountRequest)(nil),        // 7: pb.ListAccountRequest
	(*NewTokenRequest)(nil),           // 8: pb.NewTokenRequest
	(*CreateUserResponse)(nil),        // 9: pb.CreateUserResponse
	(*LoginUserResponse)(nil),         // 10: pb.LoginUserResponse
	(*GetUserDetailsResponse)(nil),    // 11: pb.GetUserDetailsResponse
	(*UpdateUserResponse)(nil),        // 12: pb.UpdateUserResponse
	(*VerifyUserResponse)(nil),        // 13: pb.VerifyUserResponse
	(*CreateAccountResponse)(nil),     // 14: pb.CreateAccountResponse
	(*GetAccountDetailsResponse)(nil), // 15: pb.GetAccountDetailsResponse
	(*ListAccountResponse)(nil),       // 16: pb.ListAccountResponse
	(*NewTokenResponse)(nil),          // 17: pb.NewTokenResponse
}
var file_rpc_simple_bank_proto_depIdxs = []int32{
	0,  // 0: pb.SimpleBank.CreateUser:input_type -> pb.CreateUserRequest
	1,  // 1: pb.SimpleBank.Login:input_type -> pb.LoginUserRequest
	2,  // 2: pb.SimpleBank.GetUserDetails:input_type -> pb.GetUserDetailsRequest
	3,  // 3: pb.SimpleBank.UpdateUser:input_type -> pb.UpdateUserRequest
	4,  // 4: pb.SimpleBank.VerifyUser:input_type -> pb.VerifyUserRequest
	5,  // 5: pb.SimpleBank.CreateAccount:input_type -> pb.CreateAccountRequest
	6,  // 6: pb.SimpleBank.GetAccountDetails:input_type -> pb.Empty
	7,  // 7: pb.SimpleBank.ListAccounts:input_type -> pb.ListAccountRequest
	8,  // 8: pb.SimpleBank.IssueNewToken:input_type -> pb.NewTokenRequest
	9,  // 9: pb.SimpleBank.CreateUser:output_type -> pb.CreateUserResponse
	10, // 10: pb.SimpleBank.Login:output_type -> pb.LoginUserResponse
	11, // 11: pb.SimpleBank.GetUserDetails:output_type -> pb.GetUserDetailsResponse
	12, // 12: pb.SimpleBank.UpdateUser:output_type -> pb.UpdateUserResponse
	13, // 13: pb.SimpleBank.VerifyUser:output_type -> pb.VerifyUserResponse
	14, // 14: pb.SimpleBank.CreateAccount:output_type -> pb.CreateAccountResponse
	15, // 15: pb.SimpleBank.GetAccountDetails:output_type -> pb.GetAccountDetailsResponse
	16, // 16: pb.SimpleBank.ListAccounts:output_type -> pb.ListAccountResponse
	17, // 17: pb.SimpleBank.IssueNewToken:output_type -> pb.NewTokenResponse
	9,  // [9:18] is the sub-list for method output_type
	0,  // [0:9] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_rpc_simple_bank_proto_init() }
func file_rpc_simple_bank_proto_init() {
	if File_rpc_simple_bank_proto != nil {
		return
	}
	file_user_proto_init()
	file_account_proto_init()
	file_token_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_simple_bank_proto_rawDesc), len(file_rpc_simple_bank_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_simple_bank_proto_goTypes,
		DependencyIndexes: file_rpc_simple_bank_proto_depIdxs,
	}.Build()
	File_rpc_simple_bank_proto = out.File
	file_rpc_simple_bank_proto_goTypes = nil
	file_rpc_simple_bank_proto_depIdxs = nil
}
